{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   AssertionError\n", "test_name": "test_opencontactForm", "rerun": "0"}, "1": {"status": "FAIL", "message": "       http.client.RemoteDisconnected: Remote end closed connection without response\n       urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000235B0021F70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session/a77b5e70-dd01-4bb2-bd8c-b786b59de2b4/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235B0021F70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000235B0021C40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session/a77b5e70-dd01-4bb2-bd8c-b786b59de2b4/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235B0021C40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_enterDataInForm", "rerun": "0"}}, "suite_name": "ContectFormTest.py"}}}, "date": "June 26, 2022", "start_time": 1656241227.0854392, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}